"""AutoMix banner art - GENERATED by scripts/pixart_image_integrator.py. Do not edit by hand.

WORDMARK: cfonts 'block' AUTOMIX rows (recoloured at render time).
PALETTE:  letter -> hex colour. ' ' (space) is the transparent background.
FRAMES:   0 frame(s), each 0 rows x 0 cols of palette letters; 2 px/cell via half-blocks.
FRAME_MS: ms per frame (0 = static single image; >0 = cycle the frames).
RECOLOR:  n/a (no image - wordmark only).
"""

WORDMARK = [
    '  █████╗  ██╗   ██╗ ████████╗  ██████╗  ███╗   ███╗ ██╗ ██╗  ██╗',
    ' ██╔══██╗ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ████╗ ████║ ██║ ╚██╗██╔╝',
    ' ███████║ ██║   ██║    ██║    ██║   ██║ ██╔████╔██║ ██║  ╚███╔╝',
    ' ██╔══██║ ██║   ██║    ██║    ██║   ██║ ██║╚██╔╝██║ ██║  ██╔██╗',
    ' ██║  ██║ ╚██████╔╝    ██║    ╚██████╔╝ ██║ ╚═╝ ██║ ██║ ██╔╝ ██╗',
    ' ╚═╝  ╚═╝  ╚═════╝     ╚═╝     ╚═════╝  ╚═╝     ╚═╝ ╚═╝ ╚═╝  ╚═╝',
]

BACKGROUND = None  # detected background -> transparent in the banner
FRAME_MS = 0

PALETTE = {
}

FRAMES = [
]
