"""AutoMix banner art - GENERATED by scripts/pixart_image_integrator.py. Do not edit by hand.

WORDMARK: cfonts 'block' AUTOMIX rows (recoloured at render time).
PALETTE:  letter -> hex colour. ' ' (space) is the transparent background.
GRID:     12 rows x 10 cols of palette letters; rendered 2 px/cell via half-blocks.
RECOLOR:  on - hues=green,cyan,yellow,magenta levels=5 (neon UI palette).
"""

WORDMARK = [
    '  █████╗  ██╗   ██╗ ████████╗  ██████╗  ███╗   ███╗ ██╗ ██╗  ██╗',
    ' ██╔══██╗ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ████╗ ████║ ██║ ╚██╗██╔╝',
    ' ███████║ ██║   ██║    ██║    ██║   ██║ ██╔████╔██║ ██║  ╚███╔╝',
    ' ██╔══██║ ██║   ██║    ██║    ██║   ██║ ██║╚██╔╝██║ ██║  ██╔██╗',
    ' ██║  ██║ ╚██████╔╝    ██║    ╚██████╔╝ ██║ ╚═╝ ██║ ██║ ██╔╝ ██╗',
    ' ╚═╝  ╚═╝  ╚═════╝     ╚═╝     ╚═════╝  ╚═╝     ╚═╝ ╚═╝ ╚═╝  ╚═╝',
]

BACKGROUND = '#638596'  # detected background -> transparent in the banner

PALETTE = {
    'a': '#002e0c',
    'b': '#918006',
    'c': '#5e5404',
}

GRID = [
    '  a   aa  ',
    ' aaaaaaaa ',
    ' aaaaaaaa ',
    'aaaababaa ',
    ' aabbbbba ',
    '  ababbaa ',
    ' aabbbbba ',
    '  acbbbc  ',
    '  accccc  ',
    '  accccc  ',
    '  abaaa   ',
    '  aba     ',
]
