"""AutoMix banner art - GENERATED by scripts/pixart_image_integrator.py. Do not edit by hand.

WORDMARK: cfonts 'block' AUTOMIX rows (recoloured at render time).
PALETTE:  letter -> hex colour. ' ' (space) is the transparent background.
GRID:     12 rows x 13 cols of palette letters; rendered 2 px/cell via half-blocks.
RECOLOR:  on - hues=green,cyan,yellow,magenta levels=5 (neon UI palette).
"""

WORDMARK = [
    '  █████╗  ██╗   ██╗ ████████╗  ██████╗  ███╗   ███╗ ██╗ ██╗  ██╗',
    ' ██╔══██╗ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ████╗ ████║ ██║ ╚██╗██╔╝',
    ' ███████║ ██║   ██║    ██║    ██║   ██║ ██╔████╔██║ ██║  ╚███╔╝',
    ' ██╔══██║ ██║   ██║    ██║    ██║   ██║ ██║╚██╔╝██║ ██║  ██╔██╗',
    ' ██║  ██║ ╚██████╔╝    ██║    ╚██████╔╝ ██║ ╚═╝ ██║ ██║ ██╔╝ ██╗',
    ' ╚═╝  ╚═╝  ╚═════╝     ╚═╝     ╚═════╝  ╚═╝     ╚═╝ ╚═╝ ╚═╝  ╚═╝',
]

BACKGROUND = None  # detected background -> transparent in the banner

PALETTE = {
    'a': '#00cb34',
    'b': '#cb22aa',
}

GRID = [
    '       aa   a',
    '       aa   a',
    '       aaaaaa',
    ' aaa   aabaab',
    ' aaa   aabaab',
    'a      aaaaaa',
    'a   aaaaaaaa ',
    'a   aaaaaaaa ',
    'a  aaaaaaaaa ',
    'a  aaaaaaaaa ',
    'aa aaaaaaaaa ',
    ' aaaaaaaaaaa ',
]
